### ISSUE TITLE
문서 작성 TODO

### ISSUE THREAD

**Issue by ooooorobo** [ooooorobo/e2e-poc#14]
- [ ] 세미나 발표 자료
- [ ] 프로젝트 환경세팅 가이드
- [ ] (QA용) 테스트 작성 가이드
- [ ] (개발용) testId 시트 관리 가이드?
- [ ] (개발용) testId 설정 컨벤션
